name: nekoswap_runes Image Build And Deploy

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            commit_sha: ${{ steps.get-commit-sha.outputs.sha }}
            ecr_registry: ${{ steps.login-ecr.outputs.registry }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get short SHA
              id: get-commit-sha
              run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
                  registry: "registry.eu-central-1.aliyuncs.com"

            - name: Build and push Docker image
              env:
                  COMMIT_SHA: ${{ steps.get-commit-sha.outputs.sha }}

              run: |
                  IMAGE_URL="registry.eu-central-1.aliyuncs.com/omnifiled/frontend-monster:${COMMIT_SHA}"
                  echo $IMAGE_URL
                  docker build -t ${IMAGE_URL} -f Dockerfile.testnet .
                  docker push ${IMAGE_URL}
            - name: Update Deploy Version
              run: |
                  sed -i 's/{{IMAGE_VERSION}}/${{ steps.get-commit-sha.outputs.sha }}/g' mainfest.yaml

            - name: Deploy to k3s
              uses: steebchen/kubectl@master
              with:
                  config: ${{ secrets.NEKOSWAP_KUBE }}
                  command: apply -f mainfest.yaml --force
